### ISSUE TITLE
Now it doesn't loop, but tries to unfollow the same unexisting user all the time

### ISSUE THREAD

**Issue by DavidSelem** [LevPasha/Instagram-bot-cs#10]
http://i.imgur.com/s3BclZ8.png

Also, I see that the current way to perform is this: Starts like/comment/follow task, if the media doesn't exist anymore, it will fail and the wait time will start, wouldn't be better if the bot detects fail, tries again with the next one media ?

**Comment by LevPasha** [comment]
Hmmm... I think i fix it! It is Hard to test it, becouse can't catch this error.

**Comment by bronzeboy** [comment]
Thanks, I'll report back asap!

**Comment by bronzeboy** [comment]
@LevPasha still have the same problem, if it don't find the selected user, it will try to unfollow it again next time becasue it dosen't delete it from the log file!

http://i.imgur.com/a0whpUZ.png

**Comment by LevPasha** [comment]
@bronzeboy test last commit.

**Comment by bronzeboy** [comment]
@LevPasha Fixed this one too! Great job!

http://i.imgur.com/cribsEt.png

**Comment by DavidSelem** [comment]
Thank you so much, @LevPasha !
