### ISSUE TITLE
Infinite loop with no "stop word"

### ISSUE THREAD

**Issue by bronzeboy** [LevPasha/Instagram-bot-cs#11]
Hey, with the new update, this is what happens with no stop word

http://i.imgur.com/DBr6d1u.png

**Comment by LevPasha** [comment]
@bronzeboy ahaha, lol... It is hard day for me yestarday...

**Comment by bronzeboy** [comment]
@LevPasha np mate, you are doing a godlike work!

**Comment by LevPasha** [comment]
@bronzeboy test last commit.

**Comment by bronzeboy** [comment]
@LevPasha You solved it! Thank you very much!
