### ISSUE TITLE
Newtonsoft.Json.Linq.JValue exception

### ISSUE THREAD

**Issue by DavidSelem** [LevPasha/Instagram-bot-cs#12]
Was using my PC and I when I checked the BOT the log was looping this:

http://i.imgur.com/tgxIkXO.png

Sorry I can't elaborate more, don't know what caused this

**Comment by LevPasha** [comment]
@DavidSelem try old version, and say what iteration is this (like, follow or what)?

**Comment by DavidSelem** [comment]
Using all the iterations, but if I have to guess, I'd say is something related with the stop words.

**Comment by LevPasha** [comment]
@DavidSelem make screenshot from login to error.

**Comment by DavidSelem** [comment]
Got this today

http://i.imgur.com/Gz29nie.png <-- This happened in 1.2

http://i.imgur.com/HthM309.png <-- 1.2.1

Also, did Instagram changed their algorithm again? As you can see in the log, every media I search via #hashtag is [right now] 9hrs old, no less! And all of them >100 likes

**Comment by bronzeboy** [comment]
got the same problem, first time happened

http://imgur.com/a/8WfI8

**Comment by LevPasha** [comment]
Ok, fix it soon.

**Comment by ierogliph** [comment]
Hi. Do you do anything to fix this bug?
May be trouble with charset?

**Comment by LevPasha** [comment]
@ierogliph sorry, have no time now... Work in progress.

**Comment by Zupkin** [comment]
Hi @LevPasha
Thank you for this practical BOT with UI, but I'm also experiencing the same problem as users above.
Could you please send me the source code, so I can take a look at this bug ?

Cheers

**Comment by LevPasha** [comment]
@DavidSelem @ierogliph @Zupkin @bronzeboy Check last release https://github.com/LevPasha/Instagram-bot-cs/commit/e12c8628a1d13a96e1d24bd66eeaf3e8f26ac2b5
