### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by warzbird** [LevPasha/Instagram-bot-cs#14]
Whats your email for getting the source code for this?  Thanks!

**Comment by LevPasha** [comment]
@warzbird hi, press "Support project" button and you will see. I can give source code only for $.

**Comment by warzbird** [comment]
Ok, I donated 5 bucks on paypal

**Comment by warzbird** [comment]
Also, can pay you to help me configure Python? Trying to make a tinder bot
but when I run the script.py in command it says can't find the file.  I
installed it to the path.

**Comment by LevPasha** [comment]
@warzbird my fault, i don't say my price for source... It coast more than 5$. Write me to email (same as you donate), and we discus about source and other questions.
