### ISSUE TITLE
Wrong UserAgent

### ISSUE THREAD

**Issue by ramazk** [LevPasha/Instagram-bot-cs#15]
UserAgent in options is chosen as Instagram 9.2, but it still sending 8.4 to instagram on login.
But likes are sending with right 9.2 .

**Comment by LevPasha** [comment]
@ramazk show me screen of tab "other settings". How do you watch sending user agent?

**Comment by ramazk** [comment]
On tab "other settings" everything is ok, 9.2 there. I'm checking using Fiddler.

**Comment by LevPasha** [comment]
@ramazk strange, check it soon.

**Comment by LevPasha** [comment]
Check last release https://github.com/LevPasha/Instagram-bot-cs/commit/e12c8628a1d13a96e1d24bd66eeaf3e8f26ac2b5
