### ISSUE TITLE
The bot doesnt't unfollow anyone

### ISSUE THREAD

**Issue by Micky922** [LevPasha/Instagram-bot-cs#16]
the bot doesn't follow anyone and the next unfollow time stills 00:00:00

**Comment by LevPasha** [comment]
![image](https://cloud.githubusercontent.com/assets/9821835/18361653/618d78ca-760b-11e6-9b34-88a4452ed3d2.png)
All work fine. Bot follow as hi should. Bot ufollow only user, that hi follow before from follow time (setting on 2 tab "Other settings"). Followed user store in file \data\***-follow-list.dat

**Comment by Micky922** [comment]
So? what have i to do?

**Comment by Micky922** [comment]
i have understood now sorry
