### ISSUE TITLE
Exception! 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'text

### ISSUE THREAD

**Issue by ataturk1925** [LevPasha/Instagram-bot-cs#18]
Exception! 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'text
WHAT ERROR??

**Comment by LevPasha** [comment]
Check last release https://github.com/LevPasha/Instagram-bot-cs/commit/e12c8628a1d13a96e1d24bd66eeaf3e8f26ac2b5

**Comment by raysrays** [comment]
It still gives this error,

**Comment by CalebVaccaro** [comment]
try JValue.ToString()
