### ISSUE TITLE
some ideas 

### ISSUE THREAD

**Issue by pr0drs** [LevPasha/Instagram-bot-cs#2]
is there any way i can change delay without touching source code ?
i mean its better to put it on settings tab ,also for scraping users to follow , 
i think you must put option 'follow username's followers ' its more effective for Instagram bussiness

**Comment by LevPasha** [comment]
@pr0drs delay from what?

**Comment by pr0drs** [comment]
delay between follow and next follow :)

**Comment by pr0drs** [comment]
and also scrape users to follow

**Comment by LevPasha** [comment]
@pr0drs change "like per day" parametr. Read about parametrs here: https://github.com/LevPasha/instabot.py

**Comment by pr0drs** [comment]
how to set these parametr ?

**Comment by LevPasha** [comment]
Change it for what you need in UI.
