### ISSUE TITLE
Unfollow only bot follow checkbox is DISABLED

### ISSUE THREAD

**Issue by extrack** [LevPasha/Instagram-bot-cs#23]
Hi! 
I have a Full Version but this feature - "Unfollow only bot follow" doesnt work.
Is it under construction? Or... How it work?)

> on russian.:
> Привет вновь!)
> Не активна галочка отписки **Unfollow only bot follow**.
> Полная версия.
> Еще в разработке, или баг?)
> ver 1.2.3

![image](https://cloud.githubusercontent.com/assets/22737046/19427221/068a2c9c-945c-11e6-8c92-fab2060b7a16.png)

**Comment by LevPasha** [comment]
@extrack hi! this checkbox do nothing now.
привет. Эта галка сейчас не на что не влияет.
