### ISSUE TITLE
"Unfollow only bot follow" unclickable, it's only for full version?

### ISSUE THREAD

**Issue by bronzeboy** [LevPasha/Instagram-bot-cs#25]
Title, i read that only the "unfollow if use dosen't follow" is for full version, I'm wrong? Thanks!

**Comment by LevPasha** [comment]
Difference (Full vs GitHub): "Don't unfollow if user follow you".

**Comment by bronzeboy** [comment]
Yes I mean the unfollow only bot follow it's disable too!

**Comment by LevPasha** [comment]
Unfollow only bot follow checkbox doing nothing now. This is default parametr.
