### ISSUE TITLE
ALL TXT files and folder now gone 

### ISSUE THREAD

**Issue by brandont1** [LevPasha/Instagram-bot-cs#28]
Disappeared.. tried re downloading but it wont regen the TXT.. Anything Im missing?

**Comment by GoldenSkyRunner** [comment]
same problem. cant use commenting feature because it cant find comments.txt? i tried to just make a new comments.txt but it wouldnt find it

**Comment by brandont1** [comment]
You have to edit with notepad, keep as generated .DAT file do not convert
to .TXT ...

**Comment by GoldenSkyRunner** [comment]
o wow thank you it is working very well now
:D
