### ISSUE TITLE
everytime  it tries to follow it says bad request

### ISSUE THREAD

**Issue by Windogeabella** [LevPasha/Instagram-bot-cs#29]
40W75599G2733033C

**Comment by LevPasha** [comment]
@Windogeabella send you key. What about problem? Make screenshot with this error.

**Comment by TacticalIdiot** [comment]
dude that means you got banned on instagram for following too rapidly! instagram can also reset your password if you bot too long or something...

**Comment by TacticalIdiot** [comment]
just wait 24 hours without botting and you can bot again
