### ISSUE TITLE
Instagram bot crashing

### ISSUE THREAD

**Issue by GoldenSkyRunner** [LevPasha/Instagram-bot-cs#35]
It was working perfectly okay a few days ago. But it has started crashing randomly through they day and i dont know why. This is very annoying so please help me.

**Comment by GoldenSkyRunner** [comment]
I just updated to newest version. Hopefully that fixes it. If not i will respond again.

**Comment by GoldenSkyRunner** [comment]
it did not fix it

**Comment by LevPasha** [comment]
@GoldenSkyRunner show erroe mesage.

**Comment by GoldenSkyRunner** [comment]
it stopped the crashing problem randomly. I don't know why. For now it is good though. @LevPasha

**Comment by GoldenSkyRunner** [comment]
it is crashing again. once a day for the past 4 days

**Comment by jbarcelonap** [comment]
Hi, in my case is clear... if I set likes in 1000 a day, never crashes, in 3000 crashes randomly and in 9000 crashes in 2 hours. I set up finally on 2000 and working full day.
Why I set 9000? because I wish full working between 8 to 10 am and also between 6 and 12 pm, but I can't because on this way always crashes.
Would be very helpful to have a counter of daily given Likes by the app.
And also a way to shedule from what to what time be working :-)
But is really a great Job, congrat, and thanks for share. I've been looking many and really is the best one free to give automatic likes.

**Comment by LevPasha** [comment]
@GoldenSkyRunner try to catch it..
@jbarcelonap ok

**Comment by GoldenSkyRunner** [comment]
i keep my like count at 950 and my comment count at 95. hasn't crashed in almost 4 days running nonstop.

**Comment by GoldenSkyRunner** [comment]
i crashed sometime today while i was at school. 
where can i find an error log or something to give you?

**Comment by pendula95** [comment]
Here is the crash report I get. 
 Exception! 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'text'.
After this I have to logout and login again to start the bot.

**Comment by GoldenSkyRunner** [comment]
when mine crashes it just comes up with "Instagram Bot has stopped responding". It did it again yesterday by the way.

**Comment by LevPasha** [comment]
Hmm...

**Comment by LevPasha** [comment]
Try new instabot.pw v1.0.1

**Comment by LevPasha** [comment]
Guys?

**Comment by pendula95** [comment]
Do you really expect us to test a version of the bot that has 15 likes per hour and 1 other options per hour?

**Comment by LevPasha** [comment]
@pendula95 hmmm, you right. Write me and i give you standart key for free.

**Comment by GoldenSkyRunner** [comment]
@LevPasha i agree with @pendula95  i've been using this program for the longest time (and i have been active in the GitHub community) and i'd rather stick with my older version that crashes randomly than pay for a new version that hasn't even gotten most of the requests for enhancements.

**Comment by LevPasha** [comment]
@GoldenSkyRunner what you want?
