### ISSUE TITLE
Error. App was closed.

### ISSUE THREAD

**Issue by KeyJoo** [LevPasha/Instagram-bot-cs#47]
**Программа выполнила ошибку:**
Сигнатура проблемы:
  Имя события проблемы:	CLR20r3
  Сигнатура проблемы 01:	InstagramBot.exe
  Сигнатура проблемы 02:	1.2.4.0
  Сигнатура проблемы 03:	584659f2
  Сигнатура проблемы 04:	System
  Сигнатура проблемы 05:	4.6.1055.0
  Сигнатура проблемы 06:	563c0ff8
  Сигнатура проблемы 07:	1fe7
  Сигнатура проблемы 08:	16
  Сигнатура проблемы 09:	System.IO.IOException
  Версия ОС:	6.1.7601.2.1.0.256.1
  Код языка:	1049
  Дополнительные сведения 1:	0a9e
  Дополнительные сведения 2:	0a9e372d3b4ad19135b953a78882e789
  Дополнительные сведения 3:	0a9e
  Дополнительные сведения 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by LevPasha** [comment]
This error repeat for you?
