### ISSUE TITLE
Exception! 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'text'.

### ISSUE THREAD

**Issue by raysrays** [LevPasha/Instagram-bot-cs#49]
Hello, I keep having this issues every time I start the bot after a few minutes after the session starts this error will pop up, how do I resolve this issue please?

ERROR: Exception! 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'text'.

Thank you,

**Comment by LevPasha** [comment]
I think i fix this bug in instabot.pw v1.0.1
