### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ninja18k** [LevPasha/Instagram-bot-cs#50]
I am getting this error evry time when I start bot
Log box:
"Can't load saved settings... Could not find a part of the path 'C:\Users\Alessandro\Desktop\instabot\Instagram-bot-cs-master\data\last-login.dat'.
2/5/2017 10:01:34 PM. Try to login as ********
2/5/2017 10:01:35 PM. Handshake with Instagram success!
2/5/2017 10:01:36 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:01:46 PM. Try to login as ****************
2/5/2017 10:01:46 PM. Handshake with Instagram success!
2/5/2017 10:01:49 PM. Login success!
2/5/2017 10:02:16 PM. Start InstaBot.
2/5/2017 10:02:16 PM. Get media_id by tag: #cute.
2/5/2017 10:02:19 PM. Succes! Get 76 media_id.
2/5/2017 10:02:19 PM. Try to follow shazaorbanova2...
2/5/2017 10:02:19 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:02:19 PM. Follow shazaorbanova2 fail!
2/5/2017 10:02:20 PM. Try to like media_id 1443750806439401751...
2/5/2017 10:02:20 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:02:20 PM. Like on media_id 1443750806439401751 fail!
2/5/2017 10:02:46 PM. Stop InstaBot.
2/5/2017 10:03:48 PM. Start InstaBot.
2/5/2017 10:03:48 PM. Try to like media_id 1443750793369983924...
2/5/2017 10:03:48 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:03:48 PM. Like on media_id 1443750793369983924 fail!
2/5/2017 10:03:48 PM. Try to follow rrippedjeans...
2/5/2017 10:03:49 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:03:49 PM. Follow rrippedjeans fail!
2/5/2017 10:04:02 PM. Stop InstaBot.
2/5/2017 10:04:15 PM. Start InstaBot.
2/5/2017 10:04:15 PM. Try to like media_id 1443750780258951294...
2/5/2017 10:04:15 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:15 PM. Like on media_id 1443750780258951294 fail!
2/5/2017 10:04:15 PM. Try to follow elviscocker...
2/5/2017 10:04:16 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:16 PM. Follow elviscocker fail!
2/5/2017 10:04:16 PM. Try to comment media_id 1443750779328355955...
2/5/2017 10:04:16 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:16 PM. Comment on media_id 1443750779328355955 fail!
2/5/2017 10:04:37 PM. Stop InstaBot.
2/5/2017 10:04:37 PM. Start InstaBot.
2/5/2017 10:04:37 PM. Try to like media_id 1443750775267421045...
2/5/2017 10:04:38 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:38 PM. Like on media_id 1443750775267421045 fail!
2/5/2017 10:04:38 PM. Try to follow linda_milinda_...
2/5/2017 10:04:38 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:38 PM. Follow linda_milinda_ fail!
2/5/2017 10:04:38 PM. Try to comment media_id 1443750773489194644...
2/5/2017 10:04:38 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:38 PM. Comment on media_id 1443750773489194644 fail!
2/5/2017 10:04:47 PM. Stop InstaBot.
2/5/2017 10:04:48 PM. Start InstaBot.
2/5/2017 10:04:48 PM. Try to like media_id 1443750771141103228...
2/5/2017 10:04:48 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:48 PM. Like on media_id 1443750771141103228 fail!
2/5/2017 10:04:48 PM. Try to follow temporarilyawizard...
2/5/2017 10:04:49 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:49 PM. Follow temporarilyawizard fail!
2/5/2017 10:04:49 PM. Try to comment media_id 1443750769403783744...
2/5/2017 10:04:49 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:04:49 PM. Comment on media_id 1443750769403783744 fail!
2/5/2017 10:04:52 PM. Stop InstaBot.
2/5/2017 10:05:33 PM. Start InstaBot.
2/5/2017 10:05:33 PM. Try to like media_id 1443750766123755666...
2/5/2017 10:05:33 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:05:33 PM. Like on media_id 1443750766123755666 fail!
2/5/2017 10:05:33 PM. Try to follow stylowabezdomna...
2/5/2017 10:05:33 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:05:33 PM. Follow stylowabezdomna fail!
2/5/2017 10:05:33 PM. Find stop word "sex" on media_id 1443750758876257901!
2/5/2017 10:05:34 PM. Try to comment media_id 1443750752006566947...
2/5/2017 10:05:34 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:05:34 PM. Comment on media_id 1443750752006566947 fail!
2/5/2017 10:06:45 PM. Try to like media_id 1443750750731942429...
2/5/2017 10:06:45 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:06:45 PM. Like on media_id 1443750750731942429 fail!
2/5/2017 10:08:01 PM. Try to like media_id 1443750748198134321...
2/5/2017 10:08:01 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:08:01 PM. Like on media_id 1443750748198134321 fail!
2/5/2017 10:09:15 PM. Find stop word "fuck" on media_id 1443750748038189055!
2/5/2017 10:09:16 PM. Try to follow meowosmos...
2/5/2017 10:09:16 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:09:16 PM. Follow meowosmos fail!
2/5/2017 10:09:19 PM. Try to like media_id 1443750741906643168...
2/5/2017 10:09:19 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:09:19 PM. Like on media_id 1443750741906643168 fail!
2/5/2017 10:10:44 PM. Try to like media_id 1443750739381788859...
2/5/2017 10:10:44 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:10:45 PM. Like on media_id 1443750739381788859 fail!
2/5/2017 10:12:10 PM. Try to like media_id 1443750735102813829...
2/5/2017 10:12:10 PM. The remote server returned an error: (400) Bad Request.
2/5/2017 10:12:10 PM. Like on media_id 1443750735102813829 fail!
"
Thanks for help.

**Comment by LevPasha** [comment]
Maybee you have ban to like. Wait some time and try again.
