### ISSUE TITLE
Loop while unfollowing an unexisting user

### ISSUE THREAD

**Issue by DavidSelem** [LevPasha/Instagram-bot-cs#6]
Can't confirm because I don't know the username of the specific instagram ID#
But I think that the user account is not longer active, so is not found and the InstagramBot loops because of it

http://i.imgur.com/xsuV6FL.png

**Comment by LevPasha** [comment]
Hmm.. Look like you right.

**Comment by bronzeboy** [comment]
I have the same problem, the quickfix is to manually delete the user id into the data folder!

http://i.imgur.com/KFwbAX2.png
