### ISSUE TITLE
Помоги, 3й день не сплю

### ISSUE THREAD

**Issue by skvoshiz** [LevPasha/Instagram-bot-cs#7]
Решил написать на c# авторизацию в инсте.
Использую xNet для работы с запросами.
Все данные беру тут: https://github.com/mgp25/Instagram-API
Я уже просто не могу ничего поделать.
Я все вроде написал, все круто сделал, но залогинится не могу.

Дай плиз исходники, а то я пока не сделаю авторизацию, не перестану мучить себя. Плиз...

**Comment by skvoshiz** [comment]
Если ты очень добрый, скинь на skvoshiz@gmail.com
Я в долгу не останусь=)

Если не очень добрый, то все ровно красавчик!

**Comment by LevPasha** [comment]
<img src="https://cdn.meme.am/instances/400x/67038038.jpg">
